### ISSUE TITLE
not able to launch from https://streamlit.io/

### ISSUE THREAD

**Issue by AbhijitKuma** [baligoyem/dataqtor#1]
I tried to launch dataqtor  from https://streamlit.io/ but it fails .
![image](https://user-images.githubusercontent.com/68940269/139005136-f65edf3e-a380-4766-bb4e-fb30ec9f4e7c.png)

**Comment by youssef12347** [comment]
Same error is back. Thanks in advance.

**Comment by baligoyem** [comment]
@youssef12347 thanks for reporting. I fixed it. You can check and I hope the app is useful for you.
